name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    


    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: run command 
      run:  |
        cd dj-docker
        docker build -t jap-djangoj . 
     # run: docker push japanjot15/djangostart:japppppppppp
