name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: .

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: japanjot15/app1:latest
    - uses: addnab/docker-run-action@v3
      with:
        image: japanjot15/app1
        run: echo hello
    
    
    
    
    
    
    
    
    # - name: build
    #   run:  docker build -t japimage . 
    #  # run: docker push japanjot15/djangostart:japppppppppp
